=== TamaraLuzija/or-lab-1/OR-lab2/public/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "$id": "#products",
  "title": "Product Catalog",
  "description": "List of products with shops",
  "items": {
    "type": "object",
    "title": "Product",
    "description": "Object representing a product with a shop",
    "properties": {
      "id": {
        "type": "integer"
      },
      "name": {
        "type": "string"
      },
      "short_description": {
        "type": "string"
      },
      "main_image": {
        "type": "string"
      },
      "images": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "description": {
        "type": "string"
      },
      "price": {
        "type": "integer"
      },
      "stock": {
        "type": "integer"
      },
      "rating": {
        "type": "number"
      },
      "created_at": {
        "type": "string"
      },
      "shop_id": {
        "type": "integer"
      },
      "shop_slug": {
        "type": "string"
      },
      "shop_name": {
        "type": "string"
      },
      "shop_description": {
        "type": "string"
      },
      "shop_background_image": {
        "type": "string"
      },
      "shop_address": {
        "type": "string"
      },
      "shop_contact": {
        "type": "string"
      },
      "shop_rating": {
        "type": "number"
      },
      "shop_timezone": {
        "type": "string"
      },
      "shop_created_at": {
        "type": "string"
      }
    },
    "required": [
      "id",
      "name",
      "short_description",
      "main_image",
      "images",
      "description",
      "price",
      "stock",
      "rating",
      "created_at",
      "shop_id",
      "shop_slug",
      "shop_name",
      "shop_description",
      "shop_background_image",
      "shop_address",
      "shop_contact",
      "shop_rating",
      "shop_timezone",
      "shop_created_at"
    ]
  }
}

=== TamaraLuzija/or-lab-1/OR-lab2/public/all.json
[
  {
    "id": 10,
    "name": "Nike Pegasus Trail 3",
    "short_description": "Wet weather can't stop your daily running habit when you lace up your workhorse with wings.",
    "main_image": "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,b_rgb:f5f5f5/609263c1-2c57-4646-991e-3dc0195f2b1e/pegasus-trail-3-trail-running-shoes-kXQ1np.png",
    "description": "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
    "price": 654,
    "stock": 21,
    "created_at": "2021-04-22T06:41:50.741Z",
    "shop_id": 4,
    "shop_slug": "sport vision",
    "shop_name": "sport vision",
    "shop_description": "Consequatur a cum. Nostrum impedit ut sed cumque quidem.",
    "shop_background_image": "https://www.supernova-gardenmall.hr//fileadmin/shared/logos/Sport_Vision.png",
    "shop_address": "225 Elvie Grove",
    "shop_contact": "1-851-449-4731 x041",
    "shop_rating": 2,
    "shop_timezone": "America/Regina",
    "shop_created_at": "2021-01-27T09:09:47.966Z",
    "images": [
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,b_rgb:f5f5f5/609263c1-2c57-4646-991e-3dc0195f2b1e/pegasus-trail-3-trail-running-shoes-kXQ1np.png",
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,b_rgb:f5f5f5/49b4ad1f-d26f-4c1a-aba4-4d3567772814/pegasus-trail-3-trail-running-shoes-kXQ1np.png"
    ],
    "rating": 9
  },
  {
    "id": 12,
    "name": "Nike Air VaporMax 2021 FK",
    "short_description": "Get after those long runs with the Nike ZoomX Invincible Run Flyknit.",
    "main_image": "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,b_rgb:f5f5f5/ba694169-fd24-4473-b60d-1b1255653925/air-vapormax-2021-fk-shoes-Ttd2vN.png",
    "description": "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
    "price": 644,
    "stock": 12,
    "created_at": "2021-10-09T21:24:16.472Z",
    "shop_id": 4,
    "shop_slug": "sport vision",
    "shop_name": "sport vision",
    "shop_description": "Consequatur a cum. Nostrum impedit ut sed cumque quidem.",
    "shop_background_image": "https://www.supernova-gardenmall.hr//fileadmin/shared/logos/Sport_Vision.png",
    "shop_address": "225 Elvie Grove",
    "shop_contact": "1-851-449-4731 x041",
    "shop_rating": 2,
    "shop_timezone": "America/Regina",
    "shop_created_at": "2021-01-27T09:09:47.966Z",
    "images": [
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,b_rgb:f5f5f5/ba694169-fd24-4473-b60d-1b1255653925/air-vapormax-2021-fk-shoes-Ttd2vN.png",
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,b_rgb:f5f5f5/1b55de3d-1683-40db-b32e-77ca5d72db4c/air-vapormax-2021-fk-shoes-Ttd2vN.png"
    ],
    "rating": 10
  },
  {
    "id": 9,
    "name": "Nike Metcon 7",
    "short_description": "We brought it back and it's better than ever. The Nike Ace Summerlite.",
    "main_image": "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,b_rgb:f5f5f5/a4042d5e-4ee8-4df7-8cc8-d81d2518717d/metcon-7-training-shoes-VZcBz4.png",
    "description": "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
    "price": 554,
    "stock": 16,
    "created_at": "2021-10-16T23:07:11.029Z",
    "shop_id": 3,
    "shop_slug": "shooster",
    "shop_name": "shooster",
    "shop_description": "Et harum nesciunt ea fuga dignissimos soluta. Iusto ipsam possimus nemo officiis voluptate.",
    "shop_background_image": "https://www.supernova-zadar.hr//fileadmin/_processed_/e/5/csm_SHOOSTER_96775b6a56.jpg",
    "shop_address": "4949 Domenic Club",
    "shop_contact": "1-872-204-9601 x12122",
    "shop_rating": 2,
    "shop_timezone": "Europe/Vilnius",
    "shop_created_at": "2021-09-02T10:34:05.696Z",
    "images": [
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,b_rgb:f5f5f5/a4042d5e-4ee8-4df7-8cc8-d81d2518717d/metcon-7-training-shoes-VZcBz4.png",
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,b_rgb:f5f5f5/e8b1d646-53af-492c-964e-d726a29f6d63/metcon-7-training-shoes-VZcBz4.png"
    ],
    "rating": 9
  },
  {
    "id": 6,
    "name": "Nike Zoom Fly 4",
    "short_description": "Get after those long runs with the Nike ZoomX Invincible Run Flyknit.",
    "main_image": "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,b_rgb:f5f5f5/3dd4c47e-5edf-4bdc-aff4-edc396c3f83e/zoom-fly-4-road-running-shoes-4DCPzS.png",
    "description": "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
    "price": 985,
    "stock": 14,
    "created_at": "2021-06-26T02:11:32.699Z",
    "shop_id": 2,
    "shop_slug": "Hervis",
    "shop_name": "Hervis",
    "shop_description": "Laboriosam reprehenderit itaque ut qui ut sed voluptatem vel. Quam iure quisquam et inventore est aspernatur rerum qui.",
    "shop_background_image": "https://www.hervis.hr/shop/assets/icons/hervis.svg",
    "shop_address": "28674 Reynolds Stream",
    "shop_contact": "509.440.9422 x9300",
    "shop_rating": 2,
    "shop_timezone": "Asia/Jakarta",
    "shop_created_at": "2021-08-02T05:02:17.898Z",
    "images": [
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,b_rgb:f5f5f5/3dd4c47e-5edf-4bdc-aff4-edc396c3f83e/zoom-fly-4-road-running-shoes-4DCPzS.png",
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,b_rgb:f5f5f5/bc410864-a5f9-4fe7-861c-b020aaabaea3/zoom-fly-4-road-running-shoes-4DCPzS.png"
    ],
    "rating": 8
  },
  {
    "id": 5,
    "name": "Nike Air Zoom Pegasus 38",
    "short_description": "Get after those long runs with the Nike ZoomX Invincible Run Flyknit.",
    "main_image": "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,b_rgb:f5f5f5/03741ea3-d06b-4d79-aa32-cd1829ace65a/air-zoom-pegasus-38-road-running-shoes-Rl7WJR.png",
    "description": "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
    "price": 856,
    "stock": 3,
    "created_at": "2020-12-16T20:44:39.078Z",
    "shop_id": 2,
    "shop_slug": "Hervis",
    "shop_name": "Hervis",
    "shop_description": "Laboriosam reprehenderit itaque ut qui ut sed voluptatem vel. Quam iure quisquam et inventore est aspernatur rerum qui.",
    "shop_background_image": "https://www.hervis.hr/shop/assets/icons/hervis.svg",
    "shop_address": "28674 Reynolds Stream",
    "shop_contact": "509.440.9422 x9300",
    "shop_rating": 2,
    "shop_timezone": "Asia/Jakarta",
    "shop_created_at": "2021-08-02T05:02:17.898Z",
    "images": [
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,b_rgb:f5f5f5/03741ea3-d06b-4d79-aa32-cd1829ace65a/air-zoom-pegasus-38-road-running-shoes-Rl7WJR.png",
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,b_rgb:f5f5f5/03734348-3fcc-4a17-9080-161332584b35/air-zoom-pegasus-38-road-running-shoes-Rl7WJR.png"
    ],
    "rating": 10
  },
  {
    "id": 4,
    "name": "Nike Zoom Fly 4",
    "short_description": "We brought it back and it's better than ever. The Nike Ace Summerlite.",
    "main_image": "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,b_rgb:f5f5f5/d5bc11d4-65e7-4254-a896-ee239ee280f5/air-zoom-pegasus-38-shield-weatherised-road-running-shoes-TJhtkN.png",
    "description": "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
    "price": 764,
    "stock": 6,
    "created_at": "2021-01-28T05:44:35.442Z",
    "shop_id": 2,
    "shop_slug": "Hervis",
    "shop_name": "Hervis",
    "shop_description": "Laboriosam reprehenderit itaque ut qui ut sed voluptatem vel. Quam iure quisquam et inventore est aspernatur rerum qui.",
    "shop_background_image": "https://www.hervis.hr/shop/assets/icons/hervis.svg",
    "shop_address": "28674 Reynolds Stream",
    "shop_contact": "509.440.9422 x9300",
    "shop_rating": 2,
    "shop_timezone": "Asia/Jakarta",
    "shop_created_at": "2021-08-02T05:02:17.898Z",
    "images": [
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,b_rgb:f5f5f5/81b9ea73-9042-484d-a6d6-020f300ddbc2/air-zoom-pegasus-38-shield-weatherised-road-running-shoes-TJhtkN.png"
    ],
    "rating": 8
  },
  {
    "id": 1,
    "name": "Nike Air Zoom Alphafly NEXT",
    "short_description": "Get after those long runs with the Nike ZoomX Invincible Run Flyknit.",
    "main_image": "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/e1a47258-2d88-43ec-af27-6929c10bb702/air-zoom-alphafly-next-road-racing-shoes-mGK8M0.png",
    "description": "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
    "price": 653,
    "stock": 4,
    "created_at": "2021-09-17T13:51:56.496Z",
    "shop_id": 1,
    "shop_slug": "intersport",
    "shop_name": "intersport",
    "shop_description": "Ab quas aut. Assumenda hic consequatur illo omnis in enim sed aperiam.",
    "shop_background_image": "https://www.arenacentar.hr/wp-content/uploads/intersport.png",
    "shop_address": "81965 Lowe Passage",
    "shop_contact": "575-941-2551 x64807",
    "shop_rating": 2,
    "shop_timezone": "Etc/UTC",
    "shop_created_at": "2021-04-28T19:16:43.134Z",
    "images": [
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,b_rgb:f5f5f5/cb039b42-644a-4553-8894-386f62c367c7/air-zoom-alphafly-next-road-racing-shoes-g2tqPZ.png",
      "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,b_rgb:f5f5f5/c295f7e9-0b41-444b-907f-b98d975b7360/air-zoom-alphafly-next-road-racing-shoes-g2tqPZ.png"
    ],
    "rating": 10
  },
  {
    "id": 2,
    "name": "Nike Air Zoom Pegasus 38",
    "short_description": "Wet weather can't stop your daily running habit when you lace up your workhorse with wings.",
    "main_image": "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,b_rgb:f5f5f5/2ac4657d-4763-4998-a8ba-431b58cfb8b9/air-zoom-pegasus-38-road-running-shoes-6CWt8S.png",
